algoritmo "semnome"
// Função :
// Autor :
// Data : 27/09/2018
// Seção de Declarações 
var
m2, d1, c2, w: Inteiro
inicio
      Escreva ("Escreva o diametro do cômodo: ")
      Leia (d1)
      Escreva ("Escreva o comprimento do cômodo: ")
      Leia (c2)
      m2 <- d1*c2
      w <- m2*12
      Escreval ("A area do cômodo em m² é igual a", m2)
      Escreva ("E para iluminar o local é necessária uma luz com uma potência igual a", w,"W")
fimalgoritmo
